<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Conjuntotruefalse extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Conjuntotruefalse_model');
    } 

    /*
     * Listing of conjuntotruefalse
     */
    function index()
    {
        $data['conjuntotruefalse'] = $this->Conjuntotruefalse_model->get_all_conjuntotruefalse();
        
        $data['_view'] = 'conjuntotruefalse/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new conjuntotruefalse
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'idTrueFalseFrases' => $this->input->post('idTrueFalseFrases'),
				'idTrueFalse' => $this->input->post('idTrueFalse'),
            );
            
            $conjuntotruefalse_id = $this->Conjuntotruefalse_model->add_conjuntotruefalse($params);
            redirect('conjuntotruefalse/index');
        }
        else
        {            
            $data['_view'] = 'conjuntotruefalse/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a conjuntotruefalse
     */
    function edit($idConjuntoTrueFalse)
    {   
        // check if the conjuntotruefalse exists before trying to edit it
        $data['conjuntotruefalse'] = $this->Conjuntotruefalse_model->get_conjuntotruefalse($idConjuntoTrueFalse);
        
        if(isset($data['conjuntotruefalse']['idConjuntoTrueFalse']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'idTrueFalseFrases' => $this->input->post('idTrueFalseFrases'),
					'idTrueFalse' => $this->input->post('idTrueFalse'),
                );

                $this->Conjuntotruefalse_model->update_conjuntotruefalse($idConjuntoTrueFalse,$params);            
                redirect('conjuntotruefalse/index');
            }
            else
            {
                $data['_view'] = 'conjuntotruefalse/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The conjuntotruefalse you are trying to edit does not exist.');
    } 

    /*
     * Deleting conjuntotruefalse
     */
    function remove($idConjuntoTrueFalse)
    {
        $conjuntotruefalse = $this->Conjuntotruefalse_model->get_conjuntotruefalse($idConjuntoTrueFalse);

        // check if the conjuntotruefalse exists before trying to delete it
        if(isset($conjuntotruefalse['idConjuntoTrueFalse']))
        {
            $this->Conjuntotruefalse_model->delete_conjuntotruefalse($idConjuntoTrueFalse);
            redirect('conjuntotruefalse/index');
        }
        else
            show_error('The conjuntotruefalse you are trying to delete does not exist.');
    }
    
}
