<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dialogo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dialogo_model');
    } 

    /*
     * Listing of dialogo
     */
    function index()
    {
        $data['dialogo'] = $this->Dialogo_model->get_all_dialogo();
        
        $data['_view'] = 'dialogo/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new dialogo
     */
    function add($idLicao)
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'titulo' => $this->input->post('titulo'),
				'imagem' => $this->input->post('imagem'),
				'descricao' => $this->input->post('descricao'),
				'ordem' => $this->input->post('ordem'),
				'idLicao' => $this->input->post('idLicao'),
            );
            
            $dialogo_id = $this->Dialogo_model->add_dialogo($params);
            redirect('licao/index');
        }
        else
        {
            $data['idLicao']=$idLicao;
            $data['_view'] = 'dialogo/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a dialogo
     */
    function edit($idDialogo)
    {   
        // check if the dialogo exists before trying to edit it
        $data['dialogo'] = $this->Dialogo_model->get_dialogo($idDialogo);
        
        if(isset($data['dialogo']['idDialogo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'titulo' => $this->input->post('titulo'),
					'imagem' => $this->input->post('imagem'),
					'descricao' => $this->input->post('descricao'),
					'ordem' => $this->input->post('ordem'),
					'idLicao' => $this->input->post('idLicao'),
                );

                $this->Dialogo_model->update_dialogo($idDialogo,$params);            
                redirect('dialogo/index');
            }
            else
            {
                $data['_view'] = 'dialogo/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The dialogo you are trying to edit does not exist.');
    } 

    /*
     * Deleting dialogo
     */
    function remove($idDialogo)
    {
        $dialogo = $this->Dialogo_model->get_dialogo($idDialogo);

        // check if the dialogo exists before trying to delete it
        if(isset($dialogo['idDialogo']))
        {
            $this->Dialogo_model->delete_dialogo($idDialogo);
            redirect('dialogo/index');
        }
        else
            show_error('The dialogo you are trying to delete does not exist.');
    }
    
}
