<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Imagemfrase extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Imagemfrase_model');
        $this->load->model('Licao_model');
    } 

    /*
     * Listing of imagemfrase
     */
    function index()
    {
        $data['imagemfrase'] = $this->Imagemfrase_model->get_all_imagemfrase();
        
        $data['_view'] = 'imagemfrase/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new imagemfrase
     */
    function add($idLicao)
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'titulo' => $this->input->post('titulo'),
				'imagem' => $this->input->post('imagem'),
				'video' => $this->input->post('video'),
				'descricao' => $this->input->post('descricao'),
				'frase1' => $this->input->post('frase1'),
				'frase2' => $this->input->post('frase2'),
				'frase3' => $this->input->post('frase3'),
				'frase4' => $this->input->post('frase4'),
				'frase5' => $this->input->post('frase5'),
				'frase6' => $this->input->post('frase6'),
				'frase7' => $this->input->post('frase7'),
				'frase8' => $this->input->post('frase8'),
				'fraseCorreta' => $this->input->post('fraseCorreta'),
				'idLicao' => $idLicao,
				'ordem' => $this->Licao_model->setOrdem($idLicao),
                'tipo'=>'imagemfrase',
            );
            
            $imagemfrase_id = $this->Imagemfrase_model->add_imagemfrase($params);
            redirect('licao/index');
        }
        else
        {
            $data['idLicao']=$idLicao;
            $data['_view'] = 'imagemfrase/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a imagemfrase
     */
    function edit($idImagemFrase)
    {   
        // check if the imagemfrase exists before trying to edit it
        $data['imagemfrase'] = $this->Imagemfrase_model->get_imagemfrase($idImagemFrase);
        
        if(isset($data['imagemfrase']['idImagemFrase']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'titulo' => $this->input->post('titulo'),
					'imagem' => $this->input->post('imagem'),
					'video' => $this->input->post('video'),
					'descricao' => $this->input->post('descricao'),
					'frase1' => $this->input->post('frase1'),
					'frase2' => $this->input->post('frase2'),
					'frase3' => $this->input->post('frase3'),
					'frase4' => $this->input->post('frase4'),
					'frase5' => $this->input->post('frase5'),
					'frase6' => $this->input->post('frase6'),
					'frase7' => $this->input->post('frase7'),
					'frase8' => $this->input->post('frase8'),
					'fraseCorreta' => $this->input->post('fraseCorreta'),
					'idLicao' => $this->input->post('idLicao'),
					'ordem' => $this->Licao_model->setOrdem($this->input->post('idLicao')),
                );

                $this->Imagemfrase_model->update_imagemfrase($idImagemFrase,$params);            
                redirect('imagemfrase/index');
            }
            else
            {
                $data['_view'] = 'imagemfrase/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The imagemfrase you are trying to edit does not exist.');
    } 

    /*
     * Deleting imagemfrase
     */
    function remove($idImagemFrase)
    {
        $imagemfrase = $this->Imagemfrase_model->get_imagemfrase($idImagemFrase);

        // check if the imagemfrase exists before trying to delete it
        if(isset($imagemfrase['idImagemFrase']))
        {
            $this->Imagemfrase_model->delete_imagemfrase($idImagemFrase);
            redirect('imagemfrase/index');
        }
        else
            show_error('The imagemfrase you are trying to delete does not exist.');
    }
    
}
