<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Licao extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Licao_model');
    } 

    /*
     * Listing of licao
     */
    function index()
    {
        $data['licao'] = $this->Licao_model->get_all_licao();
        
        $data['_view'] = 'licao/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new licao
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'titulo' => $this->input->post('titulo'),
				'video' => $this->input->post('video'),
				'descricao' => $this->input->post('descricao'),
            );
            
            $licao_id = $this->Licao_model->add_licao($params);
            redirect('licao/index');
        }
        else
        {            
            $data['_view'] = 'licao/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a licao
     */
    function edit($idLicao)
    {   
        // check if the licao exists before trying to edit it
        $data['licao'] = $this->Licao_model->get_licao($idLicao);
        
        if(isset($data['licao']['idLicao']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'titulo' => $this->input->post('titulo'),
					'video' => $this->input->post('video'),
					'descricao' => $this->input->post('descricao'),
                );

                $this->Licao_model->update_licao($idLicao,$params);            
                redirect('licao/index');
            }
            else
            {
                $data['_view'] = 'licao/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The licao you are trying to edit does not exist.');
    } 

    /*
     * Deleting licao
     */
    function remove($idLicao)
    {
        $licao = $this->Licao_model->get_licao($idLicao);

        // check if the licao exists before trying to delete it
        if(isset($licao['idLicao']))
        {
            $this->Licao_model->delete_licao($idLicao);
            redirect('licao/index');
        }
        else
            show_error('The licao you are trying to delete does not exist.');
    }
    
}
