<?php error_reporting(E_ERROR | E_PARSE); ?>
<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Resposta extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Resposta_model');
        $this->load->model('Usuario_model');
        $this->load->model('Progresso_model');

    }

    /*
     * Listing of ranking
     * params $respostas é o array composto por respostaUsuario e respostaCorreta
     */
    function index($respostas,$pergunta)
    {
        //$data['resposta'] = $this->Resposta_model->get_all_resposta();
        $data['ranking'] = $this->Usuario_model->get_ranking();
        $data['pergunta']=isset($pergunta)? $pergunta: null;
        $data['respostas'] = isset($respostas)? $respostas: null;
        $data['_view'] = 'licao/ranking';
        $this->load->view('layouts/main', $data);
    }
    function rankingFinal()
    {
        //$data['resposta'] = $this->Resposta_model->get_all_resposta();
        $data['ranking'] = $this->Usuario_model->get_ranking();
        $data['_view'] = 'licao/ranking';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new resposta
     */
    function add()
    {
        $pergunta=json_decode(htmlspecialchars_decode($this->input->post('pergunta')));

        if (isset($_POST) && count($_POST) > 0) {

            $data_inicio = new DateTime($this->input->post('data'));
            $data_atual = new DateTime();
            $tempo = $data_inicio->diff($data_atual)->s;
            $idUsuario = $this->session->userdata['usuario_logado'];
            $respostaCorreta = $this->input->post('respostaCorreta');
            $respostaUsuario = $this->input->post('resposta');

            $arrayRespostas['0'] = array("arrayRespostaUsuario"=>$respostaUsuario, "arrayRespostaCorreta"=>$respostaCorreta);

            $pontuacao = 0;
            $dia = date("Y-m-d");
            if (strcmp($respostaUsuario, $respostaCorreta) == 0) {
                $pontuacao = round(100 / $tempo);

            }
            #SALVAR PROGRESSO
            //adicionar data e tempo 
            $this->salvarProgresso($idUsuario, $pergunta->idLicao, $pontuacao, $tempo, $dia, null, null, $pergunta->idPergunta, null);
            $this->editUsuario($idUsuario, $pontuacao);//atualiza pontuação do usuario

            $params = array(
                'idUsuario' => $idUsuario,
                'respostaCorreta' => $respostaCorreta,
                'respostaUsuario' => $respostaUsuario,
            );

            $resposta_id = $this->Resposta_model->add_resposta($params);


            $this->index($arrayRespostas,$pergunta);//mostrar ranking

        } else {
            //$data['_view'] = 'resposta/add';
            //$this->load->view('layouts/main', $data);
            //$this->index("");
        }
    }

    /*
     * salvar progresso do usuario
     * pontuacao da pergunta respondida
     */
    function salvarProgresso($idUsuario, $idLicao, $pontuacaoAtual, $tempo, $dia, $idDialogo = null, $idImagemFrase = null, $idPergunta = null, $idTrueFalse = null)
    {
        $params = array(
            'idUsuario' => $idUsuario,
            'idLicao' => $idLicao,
            'idPergunta' => $idPergunta,
            'pontuacaoAtual' => $pontuacaoAtual,
            'tempo' => $tempo,
            'dia' => $dia,
            'idDialogo' => $idDialogo,
            'idImagemFrase' => $idImagemFrase,
            'idTrueFalse' => $idTrueFalse,
        );

        $progresso_id = $this->Progresso_model->add_progresso($params);
        return;
    }

    function editUsuario($idUsuario, $pontos)
    {
        if ($pontos == 0) return;

        // check if the usuario exists before trying to edit it
        $data['usuario'] = $this->Usuario_model->get_usuario($idUsuario);
        $pontuacaoAtual = $data['usuario']['pontos'];

        if (isset($data['usuario']['idUsuario'])) {
            $params = array(
                'pontos' => $pontos + $pontuacaoAtual,
            );

            $this->Usuario_model->update_usuario($idUsuario, $params);
            return;

        } else
            show_error('The usuario you are trying to edit does not exist.');
    }


    /*
         * Adding a new resposta
         */
    function addDialogo()
    {
        //dialogo tem várias frases, vou receber todas as respostasUsuario e perguntas
        //comparar cada uma e atualizar a pontuação com a seguinte regra: numero de acertos * 100/tempo
        //salvar todas respostasUsuario e respotasCorreta

        $dialogo=json_decode(htmlspecialchars_decode($this->input->post('dialogo')));
        if (isset($_POST) && count($_POST) > 0) {

            $data_inicio = new DateTime($this->input->post('data'));
            $data_atual = new DateTime();
            $tempo = $data_inicio->diff($data_atual)->s;
            $idUsuario = $this->session->userdata['usuario_logado'];

            $pontuacao = 0;
            $quantidadeAcertos = 0;
            $dia = date("Y-m-d");

            $i = 1;
            $arrayIndexRespostas=array('arrayRespostaUsuario', 'arrayRespostaCorreta');
            $arrayRespostas = array();
            while (!empty($_POST['resposta' . $i])) {
                $respostaUsuario = $this->input->post('resposta' . $i);
                $respostaCorreta = $this->input->post('respostaCorreta' . $i);
                //$arrayRespostas[$i] = array_merge($arrayRespostas,$arrayIndexRespostas($respostaUsuario, $respostaCorreta));
                $arrayRespostas[$i]['arrayRespostaUsuario'] = $respostaUsuario;
                $arrayRespostas[$i]['arrayRespostaCorreta'] = $respostaCorreta;

                if (strcmp($respostaUsuario, $respostaCorreta) == 0) {
                    $quantidadeAcertos++;
                }
                $params = array(
                    'idUsuario' => $idUsuario,
                    'respostaCorreta' => $respostaCorreta,
                    'respostaUsuario' => $respostaUsuario,
                );
                $resposta_id = $this->Resposta_model->add_resposta($params);
                $i++;
            }
            $pontuacao = $quantidadeAcertos * round(100 / $tempo);

            $this->salvarProgresso($idUsuario, $dialogo->idLicao, $pontuacao, $tempo, $dia, $dialogo->idDialogo, null, null, null);
            $this->editUsuario($idUsuario, $pontuacao);//atualiza pontuação do usuario

            $this->index($arrayRespostas,$dialogo);//mostrar ranking

        } else {
            //$data['_view'] = 'resposta/add';
            //$this->load->view('layouts/main', $data);
            //$this->index("");
        }
    }

    function addTrueFalse()
    {
        $trueFalse=json_decode(htmlspecialchars_decode($this->input->post('trueFalse')));
        if (isset($_POST) && count($_POST) > 0) {
            $data_inicio = new DateTime($this->input->post('data'));
            $data_atual = new DateTime();
            $tempo = $data_inicio->diff($data_atual)->s;
            $idUsuario = $this->session->userdata['usuario_logado'];
            $pontuacao = 0;
            $quantidadeAcertos = 0;
            $dia = date("Y-m-d");
            $i = 1;
            $arrayRespostas = array();
            while (!empty($_POST['resposta' . $i])) {
                $respostaUsuario = $this->input->post('resposta' . $i);
                $respostaCorreta = $this->input->post('respostaCorreta' . $i);
                $arrayRespostas[$i]['arrayRespostaUsuario'] = $respostaUsuario;
                $arrayRespostas[$i]['arrayRespostaCorreta'] = $respostaCorreta;
                if (strcmp($respostaUsuario, $respostaCorreta) == 0) {
                    $quantidadeAcertos++;
                }
                $params = array(
                    'idUsuario' => $idUsuario,
                    'respostaCorreta' => $respostaCorreta,
                    'respostaUsuario' => $respostaUsuario,
                );
                $resposta_id = $this->Resposta_model->add_resposta($params);
                $i++;
            }
            $pontuacao = $quantidadeAcertos * round(100 / $tempo);

            $this->salvarProgresso($idUsuario, $trueFalse->idLicao, $pontuacao, $tempo, $dia, null, null, null, $trueFalse->idTrueFalse);
            $this->editUsuario($idUsuario, $pontuacao);//atualiza pontuação do usuario

            $this->index($arrayRespostas,$trueFalse);//mostrar ranking

        } else {
            //$data['_view'] = 'resposta/add';
            //$this->load->view('layouts/main', $data);
            //$this->index("");
        }
    }

    function addImagemFrase()
    {
        $imagemFrase=json_decode(htmlspecialchars_decode($this->input->post('imagemFrase')));
        if (isset($_POST) && count($_POST) > 0) {
            $data_inicio = new DateTime($this->input->post('data'));
            $data_atual = new DateTime();
            $tempo = $data_inicio->diff($data_atual)->s;
            $idUsuario = $this->session->userdata['usuario_logado'];
            $pontuacao = 0;
            $quantidadeAcertos = 0;
            $dia = date("Y-m-d");
            $respostaUsuario = $this->input->post('resposta');
            $respostaCorreta = $this->input->post('respostaCorreta');
            $arrayRespostas['0'] = array("arrayRespostaUsuario"=>$respostaUsuario, "arrayRespostaCorreta"=>$respostaCorreta);
            if (strcmp($respostaUsuario, $respostaCorreta) == 0) {
                $quantidadeAcertos++;
            }
            $params = array(
                'idUsuario' => $idUsuario,
                'respostaCorreta' => $respostaCorreta,
                'respostaUsuario' => $respostaUsuario,
            );
            $resposta_id = $this->Resposta_model->add_resposta($params);

            $pontuacao = $quantidadeAcertos * round(100 / $tempo);

            $this->salvarProgresso($idUsuario, $imagemFrase->idLicao, $pontuacao, $tempo, $dia, null, $imagemFrase->idImagemFrase, null, null);
            $this->editUsuario($idUsuario, $pontuacao);//atualiza pontuação do usuario
            $this->index($arrayRespostas,$imagemFrase);//mostrar ranking

        } else {
            //$data['_view'] = 'resposta/add';
            //$this->load->view('layouts/main', $data);
            //$this->index("");
        }
    }

}
