<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Truefalsefrase extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Truefalsefrase_model');
    } 

    /*
     * Listing of truefalsefrases
     */
    function index()
    {
        $data['truefalsefrases'] = $this->Truefalsefrase_model->get_all_truefalsefrases();
        
        $data['_view'] = 'truefalsefrase/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new truefalsefrase
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'frase' => $this->input->post('frase'),
				'opcaoTrue' => $this->input->post('opcaoTrue'),
				'opcaoFalse' => $this->input->post('opcaoFalse'),
				'opcaoCorreta' => $this->input->post('opcaoCorreta'),
            );
            
            $truefalsefrase_id = $this->Truefalsefrase_model->add_truefalsefrase($params);
            redirect('truefalsefrase/index');
        }
        else
        {            
            $data['_view'] = 'truefalsefrase/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a truefalsefrase
     */
    function edit($idTrueFalseFrases)
    {   
        // check if the truefalsefrase exists before trying to edit it
        $data['truefalsefrase'] = $this->Truefalsefrase_model->get_truefalsefrase($idTrueFalseFrases);
        
        if(isset($data['truefalsefrase']['idTrueFalseFrases']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'frase' => $this->input->post('frase'),
					'opcaoTrue' => $this->input->post('opcaoTrue'),
					'opcaoFalse' => $this->input->post('opcaoFalse'),
					'opcaoCorreta' => $this->input->post('opcaoCorreta'),
                );

                $this->Truefalsefrase_model->update_truefalsefrase($idTrueFalseFrases,$params);            
                redirect('truefalsefrase/index');
            }
            else
            {
                $data['_view'] = 'truefalsefrase/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The truefalsefrase you are trying to edit does not exist.');
    } 

    /*
     * Deleting truefalsefrase
     */
    function remove($idTrueFalseFrases)
    {
        $truefalsefrase = $this->Truefalsefrase_model->get_truefalsefrase($idTrueFalseFrases);

        // check if the truefalsefrase exists before trying to delete it
        if(isset($truefalsefrase['idTrueFalseFrases']))
        {
            $this->Truefalsefrase_model->delete_truefalsefrase($idTrueFalseFrases);
            redirect('truefalsefrase/index');
        }
        else
            show_error('The truefalsefrase you are trying to delete does not exist.');
    }
    
}
