<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Conjuntodialogo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get conjuntodialogo by idConjuntoDialogo
     */
    function get_conjuntodialogo($idConjuntoDialogo)
    {
        return $this->db->get_where('ConjuntoDialogo',array('idConjuntoDialogo'=>$idConjuntoDialogo))->row_array();
    }
        
    /*
     * Get all conjuntodialogo
     */
    function get_all_conjuntodialogo()
    {
        $this->db->order_by('idConjuntoDialogo', 'desc');
        return $this->db->get('ConjuntoDialogo')->result_array();
    }
        
    /*
     * function to add new conjuntodialogo
     */
    function add_conjuntodialogo($params)
    {
        $this->db->insert('ConjuntoDialogo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update conjuntodialogo
     */
    function update_conjuntodialogo($idConjuntoDialogo,$params)
    {
        $this->db->where('idConjuntoDialogo',$idConjuntoDialogo);
        return $this->db->update('ConjuntoDialogo',$params);
    }
    
    /*
     * function to delete conjuntodialogo
     */
    function delete_conjuntodialogo($idConjuntoDialogo)
    {
        return $this->db->delete('ConjuntoDialogo',array('idConjuntoDialogo'=>$idConjuntoDialogo));
    }

}
