<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Imagemfrase_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get imagemfrase by idImagemFrase
     */
    function get_imagemfrase($idImagemFrase)
    {
        return $this->db->get_where('ImagemFrase',array('idImagemFrase'=>$idImagemFrase))->row_array();
    }
        
    /*
     * Get all imagemfrase
     */
    function get_all_imagemfrase()
    {
        $this->db->order_by('idImagemFrase', 'desc');
        return $this->db->get('ImagemFrase')->result_array();
    }
        
    /*
     * function to add new imagemfrase
     */
    function add_imagemfrase($params)
    {
        $this->db->insert('ImagemFrase',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update imagemfrase
     */
    function update_imagemfrase($idImagemFrase,$params)
    {
        $this->db->where('idImagemFrase',$idImagemFrase);
        return $this->db->update('ImagemFrase',$params);
    }
    
    /*
     * function to delete imagemfrase
     */
    function delete_imagemfrase($idImagemFrase)
    {
        return $this->db->delete('ImagemFrase',array('idImagemFrase'=>$idImagemFrase));
    }
}
