<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pergunta_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pergunta by idPergunta
     */
    function get_pergunta($idPergunta)
    {
        return $this->db->get_where('Pergunta',array('idPergunta'=>$idPergunta))->row_array();
    }
        
    /*
     * Get all pergunta
     */
    function get_all_pergunta()
    {
        $this->db->order_by('idPergunta', 'desc');
        return $this->db->get('Pergunta')->result_array();
    }
        
    /*
     * function to add new pergunta
     */
    function add_pergunta($params)
    {
        $this->db->insert('Pergunta',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pergunta
     */
    function update_pergunta($idPergunta,$params)
    {
        $this->db->where('idPergunta',$idPergunta);
        return $this->db->update('Pergunta',$params);
    }
    
    /*
     * function to delete pergunta
     */
    function delete_pergunta($idPergunta)
    {
        return $this->db->delete('Pergunta',array('idPergunta'=>$idPergunta));
    }
}
