<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Progresso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get progresso by idProgresso
     */
    function get_progresso($idProgresso)
    {
        return $this->db->get_where('Progresso',array('idProgresso'=>$idProgresso))->row_array();
    }
        
    /*
     * Get all progresso
     */
    function get_all_progresso()
    {
        $this->db->order_by('idProgresso', 'desc');
        return $this->db->get('Progresso')->result_array();
    }
        
    /*
     * function to add new progresso
     */
    function add_progresso($params)
    {
        $this->db->insert('Progresso',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update progresso
     */
    function update_progresso($idProgresso,$params)
    {
        $this->db->where('idProgresso',$idProgresso);
        return $this->db->update('Progresso',$params);
    }
    
    /*
     * function to delete progresso
     */
    function delete_progresso($idProgresso)
    {
        return $this->db->delete('Progresso',array('idProgresso'=>$idProgresso));
    }
}
