<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Ultimapergunta_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * get ultima pergunta respondida
     */

    function get_ultimapergunta($idUsuario, $idLicao)
    {
        return $this->db->get_where('UltimaResposta', array('idUsuario' => $idUsuario, 'idLicao' => $idLicao))->row_array();
    }

    /*
     * function to update ultima resposta
     * params: idUsuario, idLicao, ordem
     * atualizar a cada resposta, qual a ultima pergunta respondida
     */
    function update_ultimapergunta($idUsuario, $idLicao, $ordem)
    {
        if ($this->get_ultimapergunta($idUsuario, $idLicao)) {
            $params = array('ordem' => $ordem);
            $this->db->where('idUsuario', $idUsuario, 'idLicao', $idLicao, 'ordem', $ordem);
            $this->db->update('UltimaResposta', $params);
            return true;
        }
        $params = array('idUsuario' => $idUsuario, 'idLicao' => $idLicao, 'ordem' => $ordem);
        $this->db->insert('UltimaResposta', $params);
        return $this->db->insert_id();
    }

    function get_licoes_feitas($idUsuario)
    {
        $this->db->select('idLicao');
        return $this->db->get_where('UltimaResposta', array('idUsuario' => $idUsuario))->result_array();
    }

    function delete_ultima_pergunta($idLicao, $idUsuario)
    {
        return $this->db->delete('UltimaResposta', array('idLicao' => $idLicao, 'idUsuario' => $idUsuario));
    }
}
