<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get usuario by nome
     */
    function get_usuario_nome($nome,$turma)
    {
        return $this->db->get_where('Usuario',array('nome'=>$nome, 'turma'=>$turma))->row_array();
    }


    /*
     * Get usuario by idUsuario
     */
    function get_usuario($idUsuario)
    {
        return $this->db->get_where('Usuario',array('idUsuario'=>$idUsuario))->row_array();
    }
        
    /*
     * Get all usuario
     */
    function get_all_usuario()
    {
        $this->db->order_by('idUsuario', 'desc');
        return $this->db->get('Usuario')->result_array();
    }
        
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('Usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($idUsuario,$params)
    {
        $this->db->where('idUsuario',$idUsuario);
        return $this->db->update('Usuario',$params);
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($idUsuario)
    {
        return $this->db->delete('Usuario',array('idUsuario'=>$idUsuario));
    }

    /*
     * function to get ranking
     */
    function get_ranking($idLicao){

        $sql="SELECT Usuario.nome,Usuario.pontos FROM UltimaResposta join Usuario on Usuario.idUsuario = UltimaResposta.idUsuario WHERE idLicao=".$idLicao." and Usuario.turma='".$this->session->userdata['turma']. "' and Usuario.ano_cadastro like ".$this->session->userdata['ano_cadastro']."  ORDER by Usuario.pontos DESC";
        return $this->db->query($sql)->result_array();
    }
}
